#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Парсер новостей с использованием библиотеки g4f
Получает актуальные новости по темам: маркетинг, технологии, реклама, ИИ, социальные сети
"""

import g4f
import re
from datetime import datetime
from typing import List, Dict


class NewsParser:
    """Класс для парсинга новостей с помощью g4f"""
    
    def __init__(self):
        self.topics = [
            "маркетинг",
            "технологии", 
            "реклама",
            "искусственный интеллект",
            "социальные сети"
        ]
        
        # Промпт для получения новостей
        self.news_prompt = (
            "Составь свежую и сжатую еженедельную подборку новостей (5–7 штук) "
            "по темам: маркетинг, технологии, реклама, искусственный интеллект, социальные сети. "
            "Упоминай только действительно новые события. Без лишней воды. "
            "Для каждой новости укажи:\n"
            "1. Заголовок\n"
            "2. Краткое описание (1-2 предложения)\n"
            "3. Дату публикации\n"
            "4. Источник (название)\n"
            "5. Ссылку на оригинал\n\n"
            "Формат вывода:\n"
            "📰 ЗАГОЛОВОК\n"
            "📝 Описание новости\n"
            "📅 Дата: [дата]\n"
            "📢 Источник: [название источника]\n"
            "🔗 Ссылка: [ссылка]\n"
            "---\n"
        )
        
        # Стиль общения ИИ
        self.bot_style = (
            "Ты — ИИ-журналист, который пишет кратко, по делу и без рекламы. "
            "Отвечай в нейтральном деловом стиле. Не указывай вымышленные источники и ссылки. "
            "Используй только реальные, актуальные новости за последнюю неделю."
        )
    
    def filter_advertisements(self, response_text: str) -> str:
        """Удаление рекламы из ответа"""
        unwanted_phrases = [
            "Generated by BLACKBOX.AI",
            "try unlimited chat https://www.blackbox.ai",
            "Generated by AI",
            "Powered by AI",
            "Created with AI",
            "Disclaimer:",
            "Note: This content",
            "Please note:",
            "AI-generated content"
        ]
        
        for phrase in unwanted_phrases:
            response_text = response_text.replace(phrase, "")
        
        # Удаляем лишние пробелы и переносы строк
        response_text = re.sub(r'\n\s*\n\s*\n', '\n\n', response_text)
        return response_text.strip()
    
    def get_news_response(self) -> str:
        """Получение ответа от g4f с новостями"""
        messages = [
            {"role": "system", "content": self.bot_style},
            {"role": "user", "content": self.news_prompt}
        ]
        
        try:
            response = g4f.ChatCompletion.create(
                model=g4f.models.gpt_4,
                messages=messages,
                stream=False,
                timeout=30
            )
            return self.filter_advertisements(response)
        
        except Exception as e:
            return f"Ошибка при получении новостей: {str(e)}"
    
    def parse_news_structure(self, news_text: str) -> List[Dict]:
        """Парсинг структурированных новостей из текста"""
        news_items = []
        
        # Разделяем текст по разделителям
        sections = news_text.split('---')
        
        for section in sections:
            if not section.strip():
                continue
                
            news_item = {}
            lines = section.strip().split('\n')
            
            for line in lines:
                line = line.strip()
                if line.startswith('📰'):
                    news_item['title'] = line[1:].strip()
                elif line.startswith('📝'):
                    news_item['description'] = line[1:].strip()
                elif line.startswith('📅'):
                    news_item['date'] = line[1:].strip().replace('Дата:', '').strip()
                elif line.startswith('📢'):
                    news_item['source'] = line[1:].strip().replace('Источник:', '').strip()
                elif line.startswith('🔗'):
                    news_item['link'] = line[1:].strip().replace('Ссылка:', '').strip()
            
            # Добавляем только если есть заголовок
            if news_item.get('title'):
                news_items.append(news_item)
        
        return news_items
    
    def display_news(self, news_items: List[Dict]):
        """Красивый вывод новостей"""
        if not news_items:
            print("[ОШИБКА] Новости не найдены")
            return
        
        print("=" * 80)
        print("НОВОСТИ")
        print("=" * 80)
        print(f"Дата получения: {datetime.now().strftime('%d.%m.%Y %H:%M')}")
        print(f"Темы: {', '.join(self.topics)}")
        print("=" * 80)
        
        for i, news in enumerate(news_items, 1):
            print(f"\nНОВОСТЬ {i}")
            print("-" * 50)
            
            if news.get('title'):
                print(f"ЗАГОЛОВОК: {news['title']}")
            
            if news.get('description'):
                print(f"ОПИСАНИЕ: {news['description']}")
            
            if news.get('date'):
                print(f"ДАТА: {news['date']}")
            
            if news.get('source'):
                print(f"ИСТОЧНИК: {news['source']}")
            
            if news.get('link'):
                print(f"ССЫЛКА: {news['link']}")
            
            print("-" * 50)
    
    def run(self):
        """Основной метод запуска парсера"""
        print("[ЗАПУСК] Парсер новостей...")
        print("[ОЖИДАНИЕ] Получение актуальных новостей...")
        
        # Получаем новости
        news_response = self.get_news_response()
        
        if "Ошибка" in news_response:
            print(f"[ОШИБКА] {news_response}")
            return
        
        # Парсим структуру
        news_items = self.parse_news_structure(news_response)
        
        # Выводим результат
        if news_items:
            self.display_news(news_items)
        else:
            print("\nСЫРЫЕ НОВОСТИ (без структурирования):")
            print("-" * 50)
            print(news_response)
            print("-" * 50)


def main():
    """Главная функция"""
    try:
        parser = NewsParser()
        parser.run()
    except KeyboardInterrupt:
        print("\n\n[ОСТАНОВЛЕНО] Работа прервана пользователем")
    except Exception as e:
        print(f"\n[ОШИБКА] Критическая ошибка: {str(e)}")


if __name__ == "__main__":
    main()
